### ISSUE TITLE
Missing HTTP Client

### ISSUE THREAD

**Issue by rlqualls** [Qwinix/crowd_pay#4]
`lib/crowd_pay/base.rb:46` is using Faraday, but it is not in the `Gemfile`. Faraday can be kind of heavy, so I thought I would make this issue instead of adding Faraday it in case you prefer another HTTP client.

 ```
module ClassMethods
      def create_connection
        @@connection = Faraday.new(:url => domain) do |faraday|
          # faraday.response :logger if Rails.env.develop? || Rails.env.test? # log requests to STDOUT
          faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP

          faraday.headers['X-ApiKey'] = api_key
          faraday.headers['X-PortalKey'] = portal_key

          unless Rails.env.production?
           faraday.headers['X-ByPassValidation'] = "true"
          end
        end
      end
      ...
```

**Comment by kmanzana** [comment]
Thanks @rlqualls, but just trying to get this deployed as easily as possible without trying to minimize gem and dependency size at this point in time.  Definitely worth consideration in the future, but closing for now.
